version: '3'

services:
    mysql:
        image: mysql:5
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        env_file: .env
        environment:
            MYSQL_DATABASE: ${DB_USER}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    wordpress:
        image: wordpress:6.0-php8.0-apache
        depends_on:
            - mysql
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - wp_data:/var/www/html/wp-content
            - ./:/var/www/html/wp-content/plugins/wp-awesomemotive/
        restart: always
        env_file: .env
        environment:
            WORDPRESS_DEBUG: 1
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - mysql
        ports:
            - '8080:80'
        env_file: .env
        environment:
            PMA_HOST: ${DB_HOST}
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_USERNAME: 'root'

    mailhog:
        image: mailhog/mailhog
        ports:
            - '1025:1025'
            - '8025:8025'

volumes:
    db_data: {}
    wp_data: {}
