#!/usr/bin/env bash

if [ "$1" == "reset" ]
then
  docker-compose rm -fsv
  echo "volume reset"
  docker volume rm $(docker volume ls -q | grep wp-awesomemotive)
  docker-compose build --no-cache
fi

docker-compose -p wp-awesomemotive up -d
docker exec -it wp-awesomemotive_wordpress_1 bash
